### ISSUE TITLE
consider making dir vs directory var naming consistent

### ISSUE THREAD

**Issue by aisch** [playlist-ansible/zookeeper#8]
clearly a micro-nit but in `defaults/main.yml`:

```yaml
...
exhibitor_log_index_directory: "{{zookeeper_log_dir}}"
exhibitor_zookeeper_install_directory: "{{zookeeper_install_dir}}"
exhibitor_zookeeper_data_directory: "{{zookeeper_data_dir}}"
exhibitor_zookeeper_log_directory
...
```

these are `_directory` while everything else is `_dir`. i'd :+1: `_dir` if there was a vote.
